revrt.exceptions.revrtRuntimeError
==================================

.. currentmodule:: revrt.exceptions

.. autoexception:: revrtRuntimeError